# document: https://github.com/realm/SwiftLint

# 無効にするルール
disabled_rules:
  - multiple_closures_with_trailing_closure # 複数のクロージャーの場合でも、trailing closureを利用したいため
  - empty_enum_arguments # enumの引数を省略したいため
  - nesting # 可読性のあるネストもあるため
  - force_cast # 強制アンラップが適している場合もあるため
  - force_try # 強制アンラップが適している場合もあるため

  # opt-inルールの中で無効にするルール
  - conditional_returns_on_newline # ガード文などは簡潔に一行で記述したいため
  - discouraged_optional_collection # PHImageManagerの既存仕様のため
  - explicit_enum_raw_value # 暗黙的なraw値で問題ないため
  - explicit_type_interface # 型推論を利用したいため
  - fatal_error_message # メッセージは不要なため
  - file_header # ヘッダには特に決まりがないため
  - lower_acl_than_parent # 対応不可のため
  - no_extension_access_modifier # extension_access_modifierを優先するため
  - no_grouping_extension # グルーピングにextensionを利用したいため
  - strict_fileprivate # fileprivateを利用したいため
  - switch_case_on_newline # caseと同じ行に記述したいため
  - trailing_closure # RxSwiftのOnNextでwarningが出るため
  - cyclomatic_complexity # caseが多い場合に対応するため
  - explicit_acl # internalは省略できるため
  - explicit_top_level_acl # internalは省略できるため
  - force_unwrapping # 絶対nilにならないものもあるため
  - closure_body_length # 長く書かざるを得ない場合もあるため
  - prefixed_toplevel_constant # kを書く習慣がないため

# defaultルール以外にopt-inから採用するルール
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_count
  - empty_xctest_method
  - explicit_enum_raw_value
  - explicit_init
  - explicit_self
  - explicit_type_interface
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - nslocalizedstring_key
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Lint対象に追加するパス
included:
  - NextSunnyDay

# Lint対象から除外するパス
excluded:
  - Pods
  - Carthage
  - NextSunnyDay/*/R.generated.swift

# 1行の文字列制限
line_length:
  - 200 # warning
  - 300 # error

# 型の行数制限
type_body_length:
  - 400 # warning
  - 600 # error

# 1ファイルの行数制限
file_length:
  - 500 # warning
  - 1000 # error

# メソッドの行数制限
function_body_length:
  - 100 # warning
  - 200 # error

type_name:
  min_length: 2
  max_length: 40

identifier_name:
  allowed_symbols: "_"
  min_length: # only min_length
    warning: 1
  reporter: "xcode"
