name: CI

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - develop

env:
  DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Xcode Build
        run: set -o pipefail &&
          xcodebuild
          -sdk iphonesimulator
          -configuration Debug
          build
          | xcpretty

      - name: Xcode Test
        run: set -o pipefail &&
          xcodebuild
          -sdk iphonesimulator
          -configuration Debug
          -scheme NextSunnyDay
          -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'
          clean test
          | xcpretty --report html

      - uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/reports
